'''
Even Fibonacci numbers
Problem 2

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
'''

def generateFibonacci(n):
    fibonacci = [1,2]
    while fibonacci[-1]+fibonacci[-2] < n:
        fib = int(fibonacci[-1]) 
        fib += int(fibonacci[-2])
        fibonacci.append(fib)
    return fibonacci

#print(generateFibonacci(10000))

if __name__ == "__main__":
    fibb = generateFibonacci(4000000)
    total = 0
    for f in fibb:
        if f%2 == 0:
            total += f

    print(total)
